#file: noinspection SpellCheckingInspection
---
logger:
  type: stdout
  level: trace
  pretty: true
  styled: true
  time_format: H:mm:ss.SSS

  colors:
    level:trace:
      background: bebebe
      foreground: ffffff
    level:debug:
      background: 6699cc
      foreground: ffffff
    level:info:
      background: 77b255
      foreground: ffffff
    level:warn:
      background: ffa93d
      foreground: ffffff
    level:error:
      background: ff6961
      foreground: ffffff
    level:fatal:
      background: ff3c54
      foreground: ffffff
    time:
      background: 7878f0
      foreground: ffffff
    pid:
      background: 3c3c78
      foreground: ffffff
    tags:
      background: 7878f0
      foreground: ffffff
    message:
      foreground: 1282a2

security:
  authentication:
    heartbeat_timeout: 45000
    identify_timeout: 30000
    session_id_length: 8

  groups:
    - name: anonymous
      permissions:
        - BROADCAST_MESSAGE
        - BROADCAST_EXECUTE
      allow_login_if_no_password_set: true
    - name: admin

  users:
    - credentials:
        login: Kasefuchs
        password_hash: $2a$12$m2Z9Yc/gJB9SlKIm/.5EoOialqf.iYvZyRx52d7YuTkHeesUW5nwq
      group: admin

    - credentials:
        login: anonymous
      group: anonymous

server:
  http:
    host: 127.0.0.1
    port: 8081
