name: crosspipe
version: 0.0.1

environment:
  sdk: '>=3.0.0'

dev_dependencies:
  build_runner: ^2.4.4
  freezed: ^2.3.4
  json_serializable: ^6.7.0

dependencies:
  json_annotation: ^4.8.1
  ansicolor: ^2.0.1
  args: ^2.4.1
  bcrypt: ^1.1.3
  http: ^0.13.5
  http_status_code: ^0.0.2
  intl: ^0.18.0
  yaml: ^3.1.1
  freezed_annotation: ^2.2.0
